import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { importName, isDynamicSegment } from './naming.ts'
import { scan, type RouteNode, type RouteTree } from './scan.ts'
import { validate } from './validate.ts'

// Split only to fit the line limit. The joined text is asserted verbatim in
// tests/generate and printed in the README — split it, never reword it.
const BANNER =
  '// AUTO-GENERATED by vite-react-file-router. ' +
  'Do not edit — changes will be overwritten.'

const INDENT = '  '

/** The 404 shipped with the plugin, used when the app doesn't define one. */
const BUILT_IN_NOT_FOUND = fileURLToPath(new URL('./404.jsx', import.meta.url))

/**
 * Import specifier for `target`.
 *
 * With a `fromDir` the path is relative to it and loses its extension, which is
 * what a real file on disk wants — readable, and portable if it moves.
 *
 * Without one the module is virtual and has no directory for a relative path to
 * resolve against, so the specifier has to be absolute. The extension stays on:
 * nothing reads it, and it saves the resolver a lookup.
 */
function specifier (target: string, fromDir?: string): string {
  if (!fromDir) return target.replace(/\\/g, '/')

  const path = relative(fromDir, target)
    .replace(/\\/g, '/')
    .replace(/\.(tsx|jsx|ts|js)$/, '')

  return path.startsWith('.') ? path : `./${path}`
}

type Import = { name: string; from: string }

function collectImports (node: RouteNode, fromDir?: string): Import[] {
  const own: Import[] = []

  // Layout before Page, matching the spec's ordering.
  if (node.layout) {
    own.push({
      name: importName(node.segments, 'Layout'),
      from: specifier(node.layout, fromDir),
    })
  }

  if (node.page) {
    own.push({
      name: importName(node.segments, 'Page'),
      from: specifier(node.page, fromDir),
    })
  }

  const nested = node.children.flatMap(
    (child) => collectImports(child, fromDir),
  )

  return [...own, ...nested]
}

function line (depth: number, text: string): string {
  return INDENT.repeat(depth) + text
}

/** react-router's path syntax uses `:name`, not the directory's `$name`. */
function routeSegment (segment: string): string {
  return isDynamicSegment(segment) ? `:${segment.slice(1)}` : segment
}

/**
 * Emits one route object.
 *
 * Every node gets an index child: its own Page when it has one, otherwise the
 * 404 — a directory that exists but renders nothing would otherwise leave a
 * blank page, since the root splat can't match a path a real route claimed.
 */
function renderRoute (
  node: RouteNode,
  depth: number,
  isRoot: boolean,
): string[] {
  const lines: string[] = [line(depth, '{')]
  const body = depth + 1

  lines.push(
    line(body, `path: '${isRoot ? '/' : routeSegment(node.segment)}',`),
  )

  if (node.layout) {
    const layout = importName(node.segments, 'Layout')

    lines.push(line(body, `element: <${layout} />,`))
  }

  lines.push(line(body, 'children: ['))

  const indexElement = node.page
    ? `<${importName(node.segments, 'Page')} />`
    : '<NotFoundPage />'

  lines.push(
    line(body + 1, '{'),
    line(body + 2, 'index: true,'),
    line(body + 2, `element: ${indexElement},`),
    line(body + 1, '},'),
  )

  for (const child of node.children) {
    lines.push(...renderRoute(child, body + 1, false))
  }

  // Anything that matches no route directory at all lands here.
  if (isRoot) {
    lines.push(
      line(body + 1, '{'),
      line(body + 2, "path: '*',"),
      line(body + 2, 'element: <NotFoundPage />,'),
      line(body + 1, '},'),
    )
  }

  lines.push(line(body, '],'), line(depth, '},'))

  return lines
}

/**
 * Renders the route tree as the source of the routes module.
 *
 * `fromDir` is the directory the output will live in, which makes the imports
 * relative. Omit it for the virtual module, which has no directory.
 */
export function generate (tree: RouteTree, fromDir?: string): string {
  const imports: Import[] = [
    {
      name: 'NotFoundPage',
      from: specifier(tree.notFound ?? BUILT_IN_NOT_FOUND, fromDir),
    },
    ...collectImports(tree.root, fromDir),
  ]

  return [
    BANNER,
    "import { createBrowserRouter } from 'react-router'",
    ...imports.map(({ name, from }) => `import ${name} from '${from}'`),
    '',
    'export default createBrowserRouter([',
    ...renderRoute(tree.root, 1, true),
    '])',
    '',
  ].join('\n')
}

export type GenerateOptions = {
  /** Vite project root. */
  root: string
  /** Route components directory, relative to `root`. */
  inputPath?: string
  /**
   * Optional debug artifact, relative to `root`. The app normally imports the
   * virtual module; this is the same routes written out so you can read them.
   */
  outputPath?: string
}

export const DEFAULT_INPUT_PATH = 'src/components/app'

export function resolvePaths (options: GenerateOptions) {
  const inputDir = resolve(
    options.root,
    options.inputPath ?? DEFAULT_INPUT_PATH,
  )

  const outputFile = options.outputPath
    ? resolve(options.root, options.outputPath)
    : undefined

  // Writing into the watched tree would make the plugin retrigger itself.
  if (outputFile && !relative(inputDir, outputFile).startsWith('..')) {
    // The seam has to fall outside `outputPath must not be inside inputPath`,
    // which tests/generate matches as one phrase.
    throw new Error(
      '[vite-react-file-router] outputPath must not be inside inputPath ' +
        `(${outputFile} is inside ${inputDir})`,
    )
  }

  return {
    inputDir,
    outputFile,
  }
}

/**
 * Scans and validates. Throws with every problem it found, not just the first.
 */
export function buildRouteTree (options: GenerateOptions): RouteTree {
  const { inputDir } = resolvePaths(options)
  const tree = scan(inputDir)

  validate(tree, options.root)

  return tree
}

/**
 * Writes the debug artifact, skipping the write when the content is unchanged
 * so an unrelated file event never triggers a spurious reload.
 */
export function writeRoutesFile (tree: RouteTree, outputFile: string): boolean {
  const source = generate(tree, dirname(outputFile))

  const current = existsSync(outputFile)
    ? readFileSync(outputFile, 'utf8')
    : null

  if (current === source) return false

  mkdirSync(dirname(outputFile), { recursive: true })
  writeFileSync(outputFile, source, 'utf8')

  return true
}

