import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { importName, isDynamicSegment } from './naming.ts'
import { scan, walk, type RouteNode, type RouteTree } from './scan.ts'
import { validate } from './validate.ts'

// Split only to fit the line limit. The joined text is asserted verbatim in
// tests/generate and printed in the README — split it, never reword it.
const BANNER =
  '// AUTO-GENERATED by vite-react-file-router. ' +
  'Do not edit — changes will be overwritten.'

const INDENT = '  '

/**
 * Emitted where a Page-less directory has no `404` governing it. The status
 * text matches what react-router synthesizes for a genuine no-match, so a
 * boundary can't tell the two apart.
 *
 * `notFound` cannot collide with a generated import: `importName` returns one
 * of its literal kinds or `${prefix}_${kind}`, and every prefix starts with an
 * uppercase letter or `_`.
 */
const THROW_HELPER = [
  '/** Thrown where a Page-less directory has no 404 governing it. */',
  'const notFound = () => {',
  '  throw new Response(null, {',
  '    status: 404,',
  "    statusText: 'Not Found',",
  '  })',
  '}',
]

/**
 * Import specifier for `target`.
 *
 * With a `fromDir` the path is relative to it and loses its extension, which is
 * what a real file on disk wants — readable, and portable if it moves.
 *
 * Without one the module is virtual and has no directory for a relative path to
 * resolve against, so the specifier has to be absolute. The extension stays on:
 * nothing reads it, and it saves the resolver a lookup.
 */
function specifier (target: string, fromDir?: string): string {
  if (!fromDir) return target.replace(/\\/g, '/')

  const path = relative(fromDir, target)
    .replace(/\\/g, '/')
    .replace(/\.(tsx|jsx|ts|js)$/, '')

  return path.startsWith('.') ? path : `./${path}`
}

type Import = {
  name: string
  from: string
  /** `import * as name`, which is how a meta module's exports are read. */
  namespace?: boolean
}

function collectImports (node: RouteNode, fromDir?: string): Import[] {
  const own: Import[] = []

  // Meta, Layout, Error, Page, NotFound — the order their properties are
  // emitted in; the splat is the last child.
  if (node.meta) {
    own.push({
      name: importName(node.segments, 'Meta'),
      from: specifier(node.meta.path, fromDir),
      namespace: true,
    })
  }

  if (node.layout) {
    own.push({
      name: importName(node.segments, 'Layout'),
      from: specifier(node.layout, fromDir),
    })
  }

  if (node.error) {
    own.push({
      name: importName(node.segments, 'Error'),
      from: specifier(node.error, fromDir),
    })
  }

  if (node.page) {
    own.push({
      name: importName(node.segments, 'Page'),
      from: specifier(node.page, fromDir),
    })
  }

  if (node.notFound) {
    own.push({
      name: importName(node.segments, 'NotFound'),
      from: specifier(node.notFound, fromDir),
    })
  }

  const nested = node.children.flatMap(
    (child) => collectImports(child, fromDir),
  )

  return [...own, ...nested]
}

function line (depth: number, text: string): string {
  return INDENT.repeat(depth) + text
}

/** react-router's path syntax uses `:name`, not the directory's `$name`. */
function routeSegment (segment: string): string {
  return isDynamicSegment(segment) ? `:${segment.slice(1)}` : segment
}

/**
 * Emits one route object.
 *
 * A directory's own `404` becomes a splat child, so unmatched paths under that
 * segment render it and deeper ones win over shallower — the same nesting
 * react-router gives a hand-written config.
 *
 * Every node also gets an index child, because a splat never matches an empty
 * remainder: without one, a Page-less directory visited at its own path would
 * render an empty `<Outlet />`. It shows the same 404 that governs the segment,
 * so `/users` and `/users/deep` agree.
 *
 * A directory's `meta` and `Error` land on this object rather than on the index
 * child, so its loader runs — and its boundary catches — for everything nested
 * beneath the segment, the index child's own Page included.
 */
function renderRoute (
  node: RouteNode,
  depth: number,
  isRoot: boolean,
  inherited?: string,
): string[] {
  const lines: string[] = [line(depth, '{')]
  const body = depth + 1
  const meta = node.meta ? importName(node.segments, 'Meta') : ''

  const own = node.notFound
    ? importName(node.segments, 'NotFound')
    : undefined

  // Nearest wins: the directory's own 404, else whatever covers it from above.
  const governing = own ?? inherited

  // `id` leads: it names the route, before `path` matches it.
  if (node.meta?.exports.id) lines.push(line(body, `id: ${meta}.id,`))

  lines.push(
    line(body, `path: '${isRoot ? '/' : routeSegment(node.segment)}',`),
  )

  if (node.meta?.exports.loader) {
    lines.push(line(body, `loader: ${meta}.loader,`))
  }

  if (node.layout) {
    const layout = importName(node.segments, 'Layout')

    lines.push(line(body, `element: <${layout} />,`))
  }

  if (node.error) {
    const boundary = importName(node.segments, 'Error')

    lines.push(line(body, `errorElement: <${boundary} />,`))
  }

  lines.push(line(body, 'children: ['), line(body + 1, '{'))
  lines.push(line(body + 2, 'index: true,'))

  if (node.page) {
    const page = importName(node.segments, 'Page')

    lines.push(line(body + 2, `element: <${page} />,`))
  } else if (governing) {
    lines.push(line(body + 2, `element: <${governing} />,`))
  } else {
    // Nothing renders this path, so make it a real 404 for the boundary.
    lines.push(line(body + 2, 'loader: notFound,'))
  }

  lines.push(line(body + 1, '},'))

  for (const child of node.children) {
    lines.push(...renderRoute(child, body + 1, false, governing))
  }

  // Unmatched paths beneath this segment, when it defines its own 404.
  if (own) {
    lines.push(
      line(body + 1, '{'),
      line(body + 2, "path: '*',"),
      line(body + 2, `element: <${own} />,`),
      line(body + 1, '},'),
    )
  }

  lines.push(line(body, '],'), line(depth, '},'))

  return lines
}

/**
 * Renders the route tree as the source of the routes module.
 *
 * The module default-exports the route config and constructs no router — which
 * one to build is the app's call, and it keeps `react-router` out of the
 * emitted imports entirely.
 *
 * `fromDir` is the directory the output will live in, which makes the imports
 * relative. Omit it for the virtual module, which has no directory.
 */
export function generate (tree: RouteTree, fromDir?: string): string {
  const imports = collectImports(tree.root, fromDir)

  return [
    BANNER,
    ...imports.map(({ name, from, namespace }) => {
      const binding = namespace ? `* as ${name}` : name

      return `import ${binding} from '${from}'`
    }),
    '',
    ...(needsThrowHelper(tree.root, false) ? [...THROW_HELPER, ''] : []),
    'export default [',
    ...renderRoute(tree.root, 1, true),
    ']',
    '',
  ].join('\n')
}

/** True when some Page-less directory has no `404` at or above it. */
function needsThrowHelper (node: RouteNode, governed: boolean): boolean {
  const covered = governed || Boolean(node.notFound)

  if (!node.page && !covered) return true

  return node.children.some((child) => needsThrowHelper(child, covered))
}

export type GenerateOptions = {
  /** Vite project root. */
  root: string
  /** Route components directory, relative to `root`. */
  inputPath?: string
  /**
   * Optional debug artifact, relative to `root`. The app normally imports the
   * virtual module; this is the same routes written out so you can read them.
   */
  outputPath?: string
}

export const DEFAULT_INPUT_PATH = 'src/components/app'

export function resolvePaths (options: GenerateOptions) {
  const inputDir = resolve(
    options.root,
    options.inputPath ?? DEFAULT_INPUT_PATH,
  )

  const outputFile = options.outputPath
    ? resolve(options.root, options.outputPath)
    : undefined

  // Writing into the watched tree would make the plugin retrigger itself.
  if (outputFile && !relative(inputDir, outputFile).startsWith('..')) {
    // The seam has to fall outside `outputPath must not be inside inputPath`,
    // which tests/generate matches as one phrase.
    throw new Error(
      '[vite-react-file-router] outputPath must not be inside inputPath ' +
        `(${outputFile} is inside ${inputDir})`,
    )
  }

  return {
    inputDir,
    outputFile,
  }
}

/**
 * Scans and validates. Throws with every problem it found, not just the first.
 */
export function buildRouteTree (options: GenerateOptions): RouteTree {
  const { inputDir } = resolvePaths(options)
  const tree = scan(inputDir)

  validate(tree, options.root)

  return tree
}

/**
 * Writes the debug artifact, skipping the write when the content is unchanged
 * so an unrelated file event never triggers a spurious reload.
 */
export function writeRoutesFile (tree: RouteTree, outputFile: string): boolean {
  const source = generate(tree, dirname(outputFile))

  const current = existsSync(outputFile)
    ? readFileSync(outputFile, 'utf8')
    : null

  if (current === source) return false

  mkdirSync(dirname(outputFile), { recursive: true })
  writeFileSync(outputFile, source, 'utf8')

  return true
}

