import { relative } from 'node:path'
import { importName } from './naming.ts'
import { exportedName, parseModule, type Node } from './parse.ts'
import { walk, type RouteNode, type RouteTree } from './scan.ts'

/** Wrappers whose return value is still a valid React component. */
const COMPONENT_WRAPPERS = new Set(['memo', 'forwardRef', 'lazy'])

/** Everything that can appear as a `default` export and still render. */
function isComponentExpression (node: Node | null | undefined): boolean {
  if (!node) return false

  switch (node.type) {
    case 'FunctionDeclaration':
    case 'FunctionExpression':
    case 'ArrowFunctionExpression':
    case 'ClassDeclaration':
    case 'ClassExpression':
      return true

    // memo(...) / forwardRef(...) / React.memo(...) / React.forwardRef(...)
    case 'CallExpression': {
      const callee = node.callee

      const name =
        callee?.type === 'MemberExpression'
          ? callee.property?.name
          : callee?.name

      return typeof name === 'string' && COMPONENT_WRAPPERS.has(name)
    }

    default:
      return false
  }
}

/**
 * Resolves a module-scope binding to its initializer. Returns `true` when the
 * binding is an import, since what it points at can't be known statically.
 */
function resolvesToComponent (body: Node[], name: string): boolean {
  for (const statement of body) {
    const node =
      statement.type === 'ExportNamedDeclaration' && statement.declaration
        ? statement.declaration
        : statement

    if (
      (node.type === 'FunctionDeclaration' ||
        node.type === 'ClassDeclaration') &&
      node.id?.name === name
    ) {
      return true
    }

    if (node.type === 'VariableDeclaration') {
      for (const declarator of node.declarations) {
        if (declarator.id?.name === name) {
          return isComponentExpression(declarator.init)
        }
      }
    }

    if (node.type === 'ImportDeclaration') {
      for (const specifier of node.specifiers) {
        if (specifier.local?.name === name) return true
      }
    }
  }

  return false
}

type DefaultExport =
  | { kind: 'missing' }
  | { kind: 'invalid' }
  | { kind: 'valid' }

function inspectDefaultExport (filePath: string): DefaultExport {
  const body = parseModule(filePath)

  for (const statement of body) {
    if (statement.type === 'ExportDefaultDeclaration') {
      const declaration = statement.declaration

      if (declaration.type === 'Identifier') {
        return resolvesToComponent(body, declaration.name)
          ? { kind: 'valid' }
          : { kind: 'invalid' }
      }

      return isComponentExpression(declaration)
        ? { kind: 'valid' }
        : { kind: 'invalid' }
    }

    if (statement.type === 'ExportNamedDeclaration') {
      const specifier = (statement.specifiers ?? []).find(
        (candidate: Node) => exportedName(candidate) === 'default',
      )

      if (!specifier) continue

      // `export { default } from './x'` — the target module isn't parsed here.
      if (statement.source) return { kind: 'valid' }

      return resolvesToComponent(body, specifier.local.name)
        ? { kind: 'valid' }
        : { kind: 'invalid' }
    }
  }

  return { kind: 'missing' }
}

/**
 * Enforces every structural requirement in one pass, collecting *all* failures
 * so a broken tree reports everything at once instead of one error per run.
 */
export function validate (tree: RouteTree, root: string): void {
  const errors: string[] = []
  const display = (target: string) => relative(root, target) || '.'
  const nodes = walk(tree.root)

  // 1. A leaf route directory with no Page can never render anything.
  for (const node of nodes) {
    if (node.children.length === 0 && !node.page) {
      errors.push(`[Error] ${display(node.dirPath)}: Page.{jsx|tsx} not found`)
    }
  }

  // 2. Distinct directories that collapse to the same import identifier.
  const claimed = new Map<string, string>()

  const claim = (name: string, dirPath: string) => {
    const existing = claimed.get(name)

    if (existing !== undefined && existing !== dirPath) {
      errors.push(
        `[Error] duplicate import name \`${name}\` generated by:\n` +
          `  ${display(existing)}\n` +
          `  ${display(dirPath)}`,
      )

      return
    }

    claimed.set(name, dirPath)
  }

  claimed.set('NotFoundPage', tree.notFound ?? '<built-in 404>')

  for (const node of nodes) {
    if (node.page) claim(importName(node.segments, 'Page'), node.dirPath)
    if (node.layout) claim(importName(node.segments, 'Layout'), node.dirPath)
    if (node.meta) claim(importName(node.segments, 'Meta'), node.dirPath)
  }

  // 3. Every component file must default-export something renderable. Meta
  // modules are deliberately absent here — they export no component.
  for (const filePath of componentFiles(tree)) {
    const result = inspectDefaultExport(filePath)

    if (result.kind === 'missing') {
      errors.push(`[Error] ${display(filePath)}: has no \`default\` export`)
    } else if (result.kind === 'invalid') {
      // Split only to fit the line limit — tests/unit/validate.test.ts and the
      // README both carry this message verbatim.
      errors.push(
        `[Error] ${display(filePath)}: ` +
          '`default` export is not a valid React component',
      )
    }
  }

  // 4. A meta module exporting neither recognized name contributes nothing, so
  // it is always a mistake rather than a no-op worth tolerating.
  for (const node of nodes) {
    if (!node.meta) continue

    const { id, loader } = node.meta.exports

    if (!id && !loader) {
      // Split only to fit the line limit — see the note on pass 3's message.
      errors.push(
        `[Error] ${display(node.meta.path)}: ` +
          'exports neither `id` nor `loader`',
      )
    }
  }

  if (errors.length > 0) throw new Error(errors.join('\n'))
}

function componentFiles (tree: RouteTree): string[] {
  const files = walk(tree.root).flatMap((node: RouteNode) =>
    [node.layout, node.page].filter((file): file is string => Boolean(file)),
  )

  return tree.notFound ? [...files, tree.notFound] : files
}
