/**
 * The spec's "Generation Use-Cases" as an executable matrix.
 *
 * Fixtures are built in temp directories rather than checked in, because
 * several cases hinge on *empty* directories, which git cannot track.
 */
import { describe, expect, test } from 'bun:test'
import { statSync } from 'node:fs'
import { dirname } from 'node:path'
import {
  buildRouteTree,
  generate,
  resolvePaths,
  writeRoutesFile,
} from '../../src/plugin/generate'
import { scan } from '../../src/plugin/scan'
import { validate } from '../../src/plugin/validate'
import { type Files, stabilize, withFixture } from '../helpers'

/**
 * Scan + validate + generate in file mode (relative imports), with the built-in
 * 404 path made stable.
 */
function sourceFor (files: Files): string {
  return withFixture(files, ({ root, inputDir, outputFile }) => {
    const tree = scan(inputDir)

    validate(tree, root)

    return stabilize(generate(tree, dirname(outputFile)))
  })
}

/**
 * The same tree rendered for the virtual module, which uses absolute imports.
 */
function virtualSourceFor (files: Files): string {
  return withFixture(files, ({ root, inputDir }) => {
    const tree = scan(inputDir)

    validate(tree, root)

    return generate(tree)
  })
}

function errorFor (files: Files): string {
  return withFixture(files, ({ root, inputDir }) => {
    try {
      validate(scan(inputDir), root)
    } catch (error) {
      return (error as Error).message
    }

    return ''
  })
}

// Deliberately an independent copy of the plugin's BANNER, split only to fit
// the line limit. The joined text must stay identical to generate.ts's.
const HEADER = [
  '// AUTO-GENERATED by vite-react-file-router. ' +
    'Do not edit — changes will be overwritten.',
  "import { createBrowserRouter } from 'react-router'",
].join('\n')

describe('use-cases that generate', () => {
  test('Root (Page-Only)', () => {
    expect(sourceFor(['Page.tsx'])).toBe(
      `${HEADER}
import NotFoundPage from '<built-in-404>'
import Page from './components/app/Page'

export default createBrowserRouter([
  {
    path: '/',
    children: [
      {
        index: true,
        element: <Page />,
      },
      {
        path: '*',
        element: <NotFoundPage />,
      },
    ],
  },
])
`,
    )
  })

  test('Root (Page and Layout)', () => {
    expect(sourceFor(['Layout.tsx', 'Page.tsx'])).toBe(
      `${HEADER}
import NotFoundPage from '<built-in-404>'
import Layout from './components/app/Layout'
import Page from './components/app/Page'

export default createBrowserRouter([
  {
    path: '/',
    element: <Layout />,
    children: [
      {
        index: true,
        element: <Page />,
      },
      {
        path: '*',
        element: <NotFoundPage />,
      },
    ],
  },
])
`,
    )
  })

  test('User-Defined 404 Component replaces the built-in', () => {
    const source = sourceFor(['404.tsx', 'Page.tsx'])

    expect(source).toContain("import NotFoundPage from './components/app/404'")
    expect(source).not.toContain('<built-in-404>')
  })

  // The root has no Page, so `/` renders the 404 rather than a blank page.
  test('Sub-Route (Page-Only)', () => {
    expect(sourceFor(['users/Page.tsx'])).toBe(
      `${HEADER}
import NotFoundPage from '<built-in-404>'
import Users_Page from './components/app/users/Page'

export default createBrowserRouter([
  {
    path: '/',
    children: [
      {
        index: true,
        element: <NotFoundPage />,
      },
      {
        path: 'users',
        children: [
          {
            index: true,
            element: <Users_Page />,
          },
        ],
      },
      {
        path: '*',
        element: <NotFoundPage />,
      },
    ],
  },
])
`,
    )
  })

  test('Sub-Route (Page and Layout)', () => {
    expect(sourceFor(['users/Layout.tsx', 'users/Page.tsx'])).toBe(
      `${HEADER}
import NotFoundPage from '<built-in-404>'
import Users_Layout from './components/app/users/Layout'
import Users_Page from './components/app/users/Page'

export default createBrowserRouter([
  {
    path: '/',
    children: [
      {
        index: true,
        element: <NotFoundPage />,
      },
      {
        path: 'users',
        element: <Users_Layout />,
        children: [
          {
            index: true,
            element: <Users_Page />,
          },
        ],
      },
      {
        path: '*',
        element: <NotFoundPage />,
      },
    ],
  },
])
`,
    )
  })

  test('Sub-Route (Page and Layout with Root)', () => {
    const source = sourceFor(['Page.tsx', 'users/Layout.tsx', 'users/Page.tsx'])

    // The root's own Page takes the index slot instead of the 404.
    expect(source).toContain(`      {
        index: true,
        element: <Page />,
      },`)

    expect(source).not.toContain(
      "element: <NotFoundPage />,\n      },\n      {\n        path: 'users'",
    )
  })

  // Both `/` and `/users` are Page-less, so each gets its own index 404.
  test('Nested Route (Page-Only)', () => {
    expect(sourceFor(['users/:userId/Page.tsx'])).toBe(
      `${HEADER}
import NotFoundPage from '<built-in-404>'
import Users__UserId_Page from './components/app/users/:userId/Page'

export default createBrowserRouter([
  {
    path: '/',
    children: [
      {
        index: true,
        element: <NotFoundPage />,
      },
      {
        path: 'users',
        children: [
          {
            index: true,
            element: <NotFoundPage />,
          },
          {
            path: ':userId',
            children: [
              {
                index: true,
                element: <Users__UserId_Page />,
              },
            ],
          },
        ],
      },
      {
        path: '*',
        element: <NotFoundPage />,
      },
    ],
  },
])
`,
    )
  })

  test('Nested Route (Page and Layout)', () => {
    const source = sourceFor([
      'users/:userId/Layout.tsx',
      'users/:userId/Page.tsx',
    ])

    const layoutImport =
      'import Users__UserId_Layout from ' +
      "'./components/app/users/:userId/Layout'"

    expect(source).toContain(layoutImport)

    expect(source).toContain(`          {
            path: ':userId',
            element: <Users__UserId_Layout />,`)
  })

  test('Nested Route (Page and Layout with Parent Route)', () => {
    const source = sourceFor([
      'users/Page.tsx',
      'users/:userId/Layout.tsx',
      'users/:userId/Page.tsx',
    ])

    // `/users` has a Page now, so the only 404s are the root index and the
    // splat.
    expect(source.match(/element: <NotFoundPage \/>/g)).toHaveLength(2)

    expect(source).toContain(`          {
            index: true,
            element: <Users_Page />,
          },`)
  })

  test('Full Example', () => {
    expect(
      sourceFor([
        'Layout.tsx',
        'Page.tsx',
        'users/Layout.tsx',
        'users/Page.tsx',
        'users/:userId/Layout.tsx',
        'users/:userId/Page.tsx',
      ]),
    ).toBe(
      `${HEADER}
import NotFoundPage from '<built-in-404>'
import Layout from './components/app/Layout'
import Page from './components/app/Page'
import Users_Layout from './components/app/users/Layout'
import Users_Page from './components/app/users/Page'
import Users__UserId_Layout from './components/app/users/:userId/Layout'
import Users__UserId_Page from './components/app/users/:userId/Page'

export default createBrowserRouter([
  {
    path: '/',
    element: <Layout />,
    children: [
      {
        index: true,
        element: <Page />,
      },
      {
        path: 'users',
        element: <Users_Layout />,
        children: [
          {
            index: true,
            element: <Users_Page />,
          },
          {
            path: ':userId',
            element: <Users__UserId_Layout />,
            children: [
              {
                index: true,
                element: <Users__UserId_Page />,
              },
            ],
          },
        ],
      },
      {
        path: '*',
        element: <NotFoundPage />,
      },
    ],
  },
])
`,
    )
  })

  test('directories are emitted in a stable order', () => {
    const source = sourceFor([
      'users/Page.tsx',
      'photos/Page.tsx',
      'albums/Page.tsx',
    ])

    expect(source.indexOf('albums')).toBeLessThan(source.indexOf('photos'))
    expect(source.indexOf('photos')).toBeLessThan(source.indexOf('users'))
  })

  test('non-component files are ignored', () => {
    const source = sourceFor({
      'Page.tsx': 'export default function Page() { return null }',
      'styles.css': '.a {}',
      'helper.ts': 'export const x = 1',
      'Page.test.tsx': 'export default function Nope() { return null }',
    })

    expect(source).not.toContain('helper')
    expect(source).not.toContain('styles')
    expect(source.match(/^import /gm)).toHaveLength(3)
  })
})

describe('use-cases that are now errors', () => {
  test.each([
    ['Empty App Route Directory', [] as string[], 'src/components/app'],
    ['User-Defined 404 Component alone', ['404.tsx'], 'src/components/app'],
    ['Root (Layout-Only)', ['Layout.tsx'], 'src/components/app'],
    [
      'Sub-Route (Layout-Only)',
      ['users/Layout.tsx'],
      'src/components/app/users',
    ],
    [
      'Nested Route (Layout-Only)',
      ['users/:userId/Layout.tsx'],
      'src/components/app/users/:userId',
    ],
  ])('%s', (_label, files, dir) => {
    expect(errorFor(files)).toBe(`[Error] ${dir}: Page.{jsx|tsx} not found`)
  })
})

// The virtual module has no directory, so its imports have to be absolute.
// Both modes come from the same tree, which is what keeps the optional debug
// file honest — importing it gives you the same routes as the virtual module.
describe('virtual vs file rendering', () => {
  test('the virtual module imports by absolute path', () => {
    const source = virtualSourceFor(['Page.tsx', 'users/Page.tsx'])

    expect(source).toMatch(
      /^import Page from '\/.+\/components\/app\/Page\.tsx'$/m,
    )

    expect(source).toMatch(
      /^import Users_Page from '\/.+\/components\/app\/users\/Page\.tsx'$/m,
    )

    expect(source).not.toContain("from './")
  })

  test('the debug file imports relatively, without extensions', () => {
    const source = sourceFor(['Page.tsx', 'users/Page.tsx'])

    expect(source).toContain("import Page from './components/app/Page'")

    expect(source).toContain(
      "import Users_Page from './components/app/users/Page'",
    )
  })

  test('only the import specifiers differ', () => {
    const files = ['Layout.tsx', 'Page.tsx', 'users/:userId/Page.tsx']

    const strip = (source: string) =>
      source
        .split('\n')
        .filter((line) => !line.startsWith('import '))
        .join('\n')

    expect(strip(virtualSourceFor(files))).toBe(strip(sourceFor(files)))
  })
})

describe('the debug artifact', () => {
  test('is written once, then skipped while unchanged', () => {
    withFixture(['Page.tsx'], ({ root, outputFile }) => {
      const tree = buildRouteTree({ root })

      expect(writeRoutesFile(tree, outputFile)).toBe(true)

      const before = statSync(outputFile).mtimeMs

      // A no-op write would reload the browser for nothing.
      expect(writeRoutesFile(buildRouteTree({ root }), outputFile)).toBe(false)
      expect(statSync(outputFile).mtimeMs).toBe(before)
    })
  })

  test('may not sit inside inputPath, which retriggers the watcher', () => {
    withFixture(['Page.tsx'], ({ root }) => {
      expect(() =>
        resolvePaths({
          root,
          outputPath: 'src/components/app/routes.jsx',
        }),
      ).toThrow(/outputPath must not be inside inputPath/)
    })
  })

  test('is optional — no outputPath means no file', () => {
    withFixture(['Page.tsx'], ({ root }) => {
      expect(resolvePaths({ root }).outputFile).toBeUndefined()
    })
  })
})

test('a missing inputPath is reported', () => {
  withFixture(['Page.tsx'], ({ root }) => {
    expect(() => buildRouteTree({
      root,
      inputPath: 'src/nope',
    })).toThrow(
      /inputPath does not exist/,
    )
  })
})
