/**
 * The spec's "Generation Use-Cases" as an executable matrix.
 *
 * Fixtures are built in temp directories rather than checked in, because
 * several cases hinge on *empty* directories, which git cannot track.
 */
import { describe, expect, test } from 'bun:test'
import { statSync } from 'node:fs'
import { dirname } from 'node:path'
import {
  buildRouteTree,
  generate,
  resolvePaths,
  writeRoutesFile,
} from '../../src/plugin/generate'
import { scan } from '../../src/plugin/scan'
import { validate } from '../../src/plugin/validate'
import { type Files, PAGE_SOURCE, withFixture } from '../helpers'

/** Scan + validate + generate in file mode, with relative imports. */
function sourceFor (files: Files): string {
  return withFixture(files, ({ root, inputDir, outputFile }) => {
    const tree = scan(inputDir)

    validate(tree, root)

    return generate(tree, dirname(outputFile))
  })
}

/**
 * The same tree rendered for the virtual module, which uses absolute imports.
 */
function virtualSourceFor (files: Files): string {
  return withFixture(files, ({ root, inputDir }) => {
    const tree = scan(inputDir)

    validate(tree, root)

    return generate(tree)
  })
}

function errorFor (files: Files): string {
  return withFixture(files, ({ root, inputDir }) => {
    try {
      validate(scan(inputDir), root)
    } catch (error) {
      return (error as Error).message
    }

    return ''
  })
}

// Deliberately an independent copy of the plugin's BANNER, split only to fit
// the line limit. The joined text must stay identical to generate.ts's.
const HEADER =
  '// AUTO-GENERATED by vite-react-file-router. ' +
  'Do not edit — changes will be overwritten.'

describe('use-cases that generate', () => {
  test('Root (Page-Only)', () => {
    expect(sourceFor(['Page.tsx'])).toBe(
      `${HEADER}
import Page from './components/app/Page'

export default [
  {
    path: '/',
    children: [
      {
        index: true,
        element: <Page />,
      },
    ],
  },
]
`,
    )
  })

  test('Root (Page and Layout)', () => {
    expect(sourceFor(['Layout.tsx', 'Page.tsx'])).toBe(
      `${HEADER}
import Layout from './components/app/Layout'
import Page from './components/app/Page'

export default [
  {
    path: '/',
    element: <Layout />,
    children: [
      {
        index: true,
        element: <Page />,
      },
    ],
  },
]
`,
    )
  })

  test('User-Defined 404 Component becomes the root catch-all', () => {
    const source = sourceFor(['404.tsx', 'Page.tsx'])

    expect(source).toContain("import NotFound from './components/app/404'")

    expect(source).toContain(`      {
        path: '*',
        element: <NotFound />,
      },`)

    // Nothing is thrown: the root 404 governs every path beneath it.
    expect(source).not.toContain('notFound')
  })

  // The root has no Page, so `/` renders the 404 rather than a blank page.
  test('Sub-Route (Page-Only)', () => {
    expect(sourceFor(['users/Page.tsx'])).toBe(
      `${HEADER}
import Users_Page from './components/app/users/Page'

/** Thrown where a Page-less directory has no 404 governing it. */
const notFound = () => {
  throw new Response(null, {
    status: 404,
    statusText: 'Not Found',
  })
}

export default [
  {
    path: '/',
    children: [
      {
        index: true,
        loader: notFound,
      },
      {
        path: 'users',
        children: [
          {
            index: true,
            element: <Users_Page />,
          },
        ],
      },
    ],
  },
]
`,
    )
  })

  test('Sub-Route (Page and Layout)', () => {
    expect(sourceFor(['users/Layout.tsx', 'users/Page.tsx'])).toBe(
      `${HEADER}
import Users_Layout from './components/app/users/Layout'
import Users_Page from './components/app/users/Page'

/** Thrown where a Page-less directory has no 404 governing it. */
const notFound = () => {
  throw new Response(null, {
    status: 404,
    statusText: 'Not Found',
  })
}

export default [
  {
    path: '/',
    children: [
      {
        index: true,
        loader: notFound,
      },
      {
        path: 'users',
        element: <Users_Layout />,
        children: [
          {
            index: true,
            element: <Users_Page />,
          },
        ],
      },
    ],
  },
]
`,
    )
  })

  test('Sub-Route (Page and Layout with Root)', () => {
    const source = sourceFor(['Page.tsx', 'users/Layout.tsx', 'users/Page.tsx'])

    // The root's own Page takes the index slot instead of the 404.
    expect(source).toContain(`      {
        index: true,
        element: <Page />,
      },`)

    expect(source).not.toContain(
      "element: <NotFoundPage />,\n      },\n      {\n        path: 'users'",
    )
  })

  // Both `/` and `/users` are Page-less, so each gets its own index 404.
  test('Nested Route (Page-Only)', () => {
    expect(sourceFor(['users/$userId/Page.tsx'])).toBe(
      `${HEADER}
import Users__UserId_Page from './components/app/users/$userId/Page'

/** Thrown where a Page-less directory has no 404 governing it. */
const notFound = () => {
  throw new Response(null, {
    status: 404,
    statusText: 'Not Found',
  })
}

export default [
  {
    path: '/',
    children: [
      {
        index: true,
        loader: notFound,
      },
      {
        path: 'users',
        children: [
          {
            index: true,
            loader: notFound,
          },
          {
            path: ':userId',
            children: [
              {
                index: true,
                element: <Users__UserId_Page />,
              },
            ],
          },
        ],
      },
    ],
  },
]
`,
    )
  })

  test('Nested Route (Page and Layout)', () => {
    const source = sourceFor([
      'users/$userId/Layout.tsx',
      'users/$userId/Page.tsx',
    ])

    const layoutImport =
      'import Users__UserId_Layout from ' +
      "'./components/app/users/$userId/Layout'"

    expect(source).toContain(layoutImport)

    expect(source).toContain(`          {
            path: ':userId',
            element: <Users__UserId_Layout />,`)
  })

  test('Nested Route (Page and Layout with Parent Route)', () => {
    const source = sourceFor([
      'users/Page.tsx',
      'users/$userId/Layout.tsx',
      'users/$userId/Page.tsx',
    ])

    // `/users` has a Page now, so the root index is the only path with
    // nothing to render — and with no 404 file anywhere, it throws.
    expect(source.match(/loader: notFound,/g)).toHaveLength(1)
    expect(source).not.toContain("path: '*'")

    expect(source).toContain(`          {
            index: true,
            element: <Users_Page />,
          },`)
  })

  test('Full Example', () => {
    expect(
      sourceFor([
        'Layout.tsx',
        'Page.tsx',
        'users/Layout.tsx',
        'users/Page.tsx',
        'users/$userId/Layout.tsx',
        'users/$userId/Page.tsx',
      ]),
    ).toBe(
      `${HEADER}
import Layout from './components/app/Layout'
import Page from './components/app/Page'
import Users_Layout from './components/app/users/Layout'
import Users_Page from './components/app/users/Page'
import Users__UserId_Layout from './components/app/users/$userId/Layout'
import Users__UserId_Page from './components/app/users/$userId/Page'

export default [
  {
    path: '/',
    element: <Layout />,
    children: [
      {
        index: true,
        element: <Page />,
      },
      {
        path: 'users',
        element: <Users_Layout />,
        children: [
          {
            index: true,
            element: <Users_Page />,
          },
          {
            path: ':userId',
            element: <Users__UserId_Layout />,
            children: [
              {
                index: true,
                element: <Users__UserId_Page />,
              },
            ],
          },
        ],
      },
    ],
  },
]
`,
    )
  })

  test('directories are emitted in a stable order', () => {
    const source = sourceFor([
      'users/Page.tsx',
      'photos/Page.tsx',
      'albums/Page.tsx',
    ])

    expect(source.indexOf('albums')).toBeLessThan(source.indexOf('photos'))
    expect(source.indexOf('photos')).toBeLessThan(source.indexOf('users'))
  })

  // Every recognized file is present, because this is what keeps the config
  // router-agnostic — an Error boundary reads its error with useRouteError()
  // rather than through a wrapper the generator would have to import.
  test('the config is the default export, with no router construction', () => {
    const source = sourceFor([
      'Layout.tsx',
      'Error.tsx',
      'Page.tsx',
      'meta.ts',
      'users/Page.tsx',
      'users/Error.tsx',
      'users/meta.ts',
    ])

    expect(source).toContain('export default [')
    expect(source).not.toContain('createBrowserRouter')
    expect(source).not.toContain("from 'react-router'")
  })

  test('non-component files are ignored', () => {
    const source = sourceFor({
      'Page.tsx': 'export default function Page() { return null }',
      'styles.css': '.a {}',
      'helper.ts': 'export const x = 1',
      'Page.test.tsx': 'export default function Nope() { return null }',
    })

    expect(source).not.toContain('helper')
    expect(source).not.toContain('styles')
    // Just Page; the config imports nothing it did not find on disk.
    expect(source.match(/^import /gm)).toHaveLength(1)
  })
})

describe('use-cases that are now errors', () => {
  test.each([
    ['Empty App Route Directory', [] as string[], 'src/components/app'],
    ['User-Defined 404 Component alone', ['404.tsx'], 'src/components/app'],
    ['Root (Layout-Only)', ['Layout.tsx'], 'src/components/app'],
    [
      'Sub-Route (Layout-Only)',
      ['users/Layout.tsx'],
      'src/components/app/users',
    ],
    [
      'Nested Route (Layout-Only)',
      ['users/$userId/Layout.tsx'],
      'src/components/app/users/$userId',
    ],
  ])('%s', (_label, files, dir) => {
    expect(errorFor(files)).toBe(`[Error] ${dir}: Page.{jsx|tsx} not found`)
  })
})

describe('route metadata', () => {
  const ID_ONLY = "export const id = 'users'\n"
  const LOADER_ONLY = 'export async function loader () {\n  return null\n}\n'

  test('a root meta lands on the root route object', () => {
    expect(sourceFor(['Page.tsx', 'meta.ts'])).toBe(
      `${HEADER}
import * as Meta from './components/app/meta'
import Page from './components/app/Page'

export default [
  {
    id: Meta.id,
    path: '/',
    loader: Meta.loader,
    children: [
      {
        index: true,
        element: <Page />,
      },
    ],
  },
]
`,
    )
  })

  test('an id-only meta emits no loader', () => {
    const source = sourceFor({
      'Page.tsx': PAGE_SOURCE,
      'meta.ts': ID_ONLY,
    })

    expect(source).toContain('id: Meta.id,')
    expect(source).not.toContain('loader:')
  })

  // Also pins that `path` stays the first key when there is no `id` to lead.
  test('a loader-only meta emits no id', () => {
    const source = sourceFor({
      'Page.tsx': PAGE_SOURCE,
      'meta.ts': LOADER_ONLY,
    })

    expect(source).toContain(`  {
    path: '/',
    loader: Meta.loader,`)

    expect(source).not.toContain('id:')
  })

  test('meta comes before Layout and Page in a sub-route', () => {
    const source = sourceFor([
      'Page.tsx',
      'users/Layout.tsx',
      'users/Page.tsx',
      'users/meta.ts',
    ])

    expect(source).toContain(
      "import * as Users_Meta from './components/app/users/meta'\n" +
        "import Users_Layout from './components/app/users/Layout'\n" +
        "import Users_Page from './components/app/users/Page'",
    )

    expect(source).toContain(`      {
        id: Users_Meta.id,
        path: 'users',
        loader: Users_Meta.loader,
        element: <Users_Layout />,`)
  })

  // The metadata belongs to the directory's own route, not to the index child
  // that renders its Page — that is what makes a loader run for nested routes.
  test('the index child never carries the metadata', () => {
    const source = sourceFor(['Page.tsx', 'users/Page.tsx', 'users/meta.ts'])

    expect(source).toContain(`          {
            index: true,
            element: <Users_Page />,
          },`)

    expect(source.match(/loader: Users_Meta\.loader,/g)).toHaveLength(1)
  })

  test('a dynamic segment names its meta like any other file', () => {
    const source = sourceFor([
      'Page.tsx',
      'users/$userId/Page.tsx',
      'users/$userId/meta.ts',
    ])

    expect(source).toContain(
      'import * as Users__UserId_Meta from ' +
        "'./components/app/users/$userId/meta'",
    )

    expect(source).toContain('id: Users__UserId_Meta.id,')
  })

  test('a Page-less parent directory still takes its metadata', () => {
    const source = sourceFor([
      'Page.tsx',
      'users/meta.ts',
      'users/$userId/Page.tsx',
    ])

    expect(source).toContain(`      {
        id: Users_Meta.id,
        path: 'users',
        loader: Users_Meta.loader,
        children: [
          {
            index: true,
            loader: notFound,
          },`)
  })
})

describe('error boundaries', () => {
  test('a root Error boundary lands on the root route object', () => {
    expect(sourceFor(['Error.tsx', 'Page.tsx'])).toBe(
      `${HEADER}
import Error from './components/app/Error'
import Page from './components/app/Page'

export default [
  {
    path: '/',
    errorElement: <Error />,
    children: [
      {
        index: true,
        element: <Page />,
      },
    ],
  },
]
`,
    )
  })

  // `element` renders the route, `errorElement` replaces it when something
  // under it throws, so they sit together above `children`.
  test('errorElement follows element, ahead of children', () => {
    const source = sourceFor([
      'Page.tsx',
      'users/Layout.tsx',
      'users/Page.tsx',
      'users/Error.tsx',
      'users/meta.ts',
    ])

    expect(source).toContain(
      "import * as Users_Meta from './components/app/users/meta'\n" +
        "import Users_Layout from './components/app/users/Layout'\n" +
        "import Users_Error from './components/app/users/Error'\n" +
        "import Users_Page from './components/app/users/Page'",
    )

    expect(source).toContain(`      {
        id: Users_Meta.id,
        path: 'users',
        loader: Users_Meta.loader,
        element: <Users_Layout />,
        errorElement: <Users_Error />,
        children: [`)
  })

  // The boundary belongs to the directory's own route, not to the index child
  // that renders its Page — that is what lets it catch nested routes too.
  test('the index child never carries the boundary', () => {
    const source = sourceFor(['Page.tsx', 'users/Page.tsx', 'users/Error.tsx'])

    expect(source).toContain(`          {
            index: true,
            element: <Users_Page />,
          },`)

    expect(source.match(/errorElement:/g)).toHaveLength(1)
  })

  test('a Page-less parent directory still takes its boundary', () => {
    const source = sourceFor([
      'Page.tsx',
      'users/Error.tsx',
      'users/$userId/Page.tsx',
    ])

    expect(source).toContain(`      {
        path: 'users',
        errorElement: <Users_Error />,
        children: [
          {
            index: true,
            loader: notFound,
          },`)
  })

  test('a dynamic segment names its boundary like any other file', () => {
    const source = sourceFor([
      'Page.tsx',
      'users/$userId/Page.tsx',
      'users/$userId/Error.tsx',
    ])

    expect(source).toContain(
      'import Users__UserId_Error from ' +
        "'./components/app/users/$userId/Error'",
    )

    expect(source).toContain('errorElement: <Users__UserId_Error />,')
  })

  test('a directory without one emits no errorElement', () => {
    expect(sourceFor(['Page.tsx', 'users/Page.tsx'])).not.toContain(
      'errorElement',
    )
  })
})

describe('not found', () => {
  test('a nested 404 emits its own splat, and the root keeps one', () => {
    const source = sourceFor([
      '404.tsx',
      'Page.tsx',
      'users/404.tsx',
      'users/Page.tsx',
    ])

    expect(source).toContain("import NotFound from './components/app/404'")

    expect(source).toContain(
      "import Users_NotFound from './components/app/users/404'",
    )

    // The deeper splat sits inside `users`; the root's stays at the top level.
    expect(source).toContain(`          {
            path: '*',
            element: <Users_NotFound />,
          },`)

    expect(source).toContain(`      {
        path: '*',
        element: <NotFound />,
      },`)
  })

  test('a directory without its own 404 emits no splat', () => {
    const source = sourceFor(['404.tsx', 'Page.tsx', 'orders/Page.tsx'])

    // Only the root's. `/orders/nope` falls through to it by ranking.
    expect(source.match(/path: '\*',/g)).toHaveLength(1)
  })

  // `/users` and `/users/deep` are governed by the same 404, so they render
  // the same component — one through the index child, one through the splat.
  test('a Page-less directory renders the 404 that governs it', () => {
    const source = sourceFor([
      '404.tsx',
      'Page.tsx',
      'users/$userId/Page.tsx',
    ])

    expect(source).toContain(`      {
        path: 'users',
        children: [
          {
            index: true,
            element: <NotFound />,
          },`)

    expect(source).not.toContain('notFound')
  })

  test('its own 404 wins over an ancestor for the index child', () => {
    const source = sourceFor([
      '404.tsx',
      'Page.tsx',
      'users/404.tsx',
      'users/$userId/Page.tsx',
    ])

    expect(source).toContain(`          {
            index: true,
            element: <Users_NotFound />,
          },`)
  })

  test('the throw helper is emitted once, however many need it', () => {
    const source = sourceFor([
      'Page.tsx',
      'users/$userId/Page.tsx',
      'orders/$orderId/Page.tsx',
    ])

    expect(source.match(/const notFound = /g)).toHaveLength(1)
    expect(source.match(/loader: notFound,/g)).toHaveLength(2)
    expect(source).not.toContain("path: '*'")
  })

  test('no helper is emitted when a 404 covers everything', () => {
    const source = sourceFor(['404.tsx', 'Page.tsx', 'users/$userId/Page.tsx'])

    expect(source).not.toContain('const notFound')
  })

  test('a dynamic segment names its 404 like any other file', () => {
    const source = sourceFor([
      'Page.tsx',
      'users/$userId/404.tsx',
      'users/$userId/Page.tsx',
    ])

    expect(source).toContain(
      'import Users__UserId_NotFound from ' +
        "'./components/app/users/$userId/404'",
    )

    expect(source).toContain('element: <Users__UserId_NotFound />,')
  })
})

// The virtual module has no directory, so its imports have to be absolute.
// Both modes come from the same tree, which is what keeps the optional debug
// file honest — importing it gives you the same routes as the virtual module.
describe('virtual vs file rendering', () => {
  test('the virtual module imports by absolute path', () => {
    const source = virtualSourceFor(['Page.tsx', 'users/Page.tsx'])

    expect(source).toMatch(
      /^import Page from '\/.+\/components\/app\/Page\.tsx'$/m,
    )

    expect(source).toMatch(
      /^import Users_Page from '\/.+\/components\/app\/users\/Page\.tsx'$/m,
    )

    expect(source).not.toContain("from './")
  })

  // A meta module keeps its extension in the virtual module and loses it in
  // the debug file, exactly as the components do.
  test('a meta module is imported the same two ways', () => {
    const files = ['Page.tsx', 'users/Page.tsx', 'users/meta.ts']

    const absolute =
      /^import \* as Users_Meta from '\/.+\/app\/users\/meta\.ts'$/m

    expect(virtualSourceFor(files)).toMatch(absolute)

    expect(sourceFor(files)).toContain(
      "import * as Users_Meta from './components/app/users/meta'",
    )
  })

  test('the debug file imports relatively, without extensions', () => {
    const source = sourceFor(['Page.tsx', 'users/Page.tsx'])

    expect(source).toContain("import Page from './components/app/Page'")

    expect(source).toContain(
      "import Users_Page from './components/app/users/Page'",
    )
  })

  test('only the import specifiers differ', () => {
    const files = [
      'Layout.tsx',
      'Page.tsx',
      'Error.tsx',
      'meta.ts',
      'users/$userId/Page.tsx',
      'users/$userId/Error.tsx',
      'users/$userId/meta.ts',
    ]

    const strip = (source: string) =>
      source
        .split('\n')
        .filter((line) => !line.startsWith('import '))
        .join('\n')

    expect(strip(virtualSourceFor(files))).toBe(strip(sourceFor(files)))
  })
})

describe('the debug artifact', () => {
  test('is written once, then skipped while unchanged', () => {
    withFixture(['Page.tsx'], ({ root, outputFile }) => {
      const tree = buildRouteTree({ root })

      expect(writeRoutesFile(tree, outputFile)).toBe(true)

      const before = statSync(outputFile).mtimeMs

      // A no-op write would reload the browser for nothing.
      expect(writeRoutesFile(buildRouteTree({ root }), outputFile)).toBe(false)
      expect(statSync(outputFile).mtimeMs).toBe(before)
    })
  })

  test('may not sit inside inputPath, which retriggers the watcher', () => {
    withFixture(['Page.tsx'], ({ root }) => {
      expect(() =>
        resolvePaths({
          root,
          outputPath: 'src/components/app/routes.jsx',
        }),
      ).toThrow(/outputPath must not be inside inputPath/)
    })
  })

  test('is optional — no outputPath means no file', () => {
    withFixture(['Page.tsx'], ({ root }) => {
      expect(resolvePaths({ root }).outputFile).toBeUndefined()
    })
  })
})

test('a missing inputPath is reported', () => {
  withFixture(['Page.tsx'], ({ root }) => {
    expect(() => buildRouteTree({
      root,
      inputPath: 'src/nope',
    })).toThrow(
      /inputPath does not exist/,
    )
  })
})
