import { describe, expect, test } from 'bun:test'
import { scan } from '../../src/plugin/scan'
import { validate } from '../../src/plugin/validate'
import { LAYOUT_SOURCE, PAGE_SOURCE, withFixture } from '../helpers'

/** Runs validation over a fixture and returns the aggregated error message. */
function errorFor (files: Parameters<typeof withFixture>[0]): string {
  return withFixture(files, ({ root, inputDir }) => {
    try {
      validate(scan(inputDir), root)
    } catch (error) {
      return (error as Error).message
    }

    return ''
  })
}

describe('leaf-Page requirement', () => {
  test('a leaf directory without a Page is an error', () => {
    expect(errorFor({
      'users/Page.tsx': PAGE_SOURCE,
      'users/$userId/': '',
    })).toBe(
      '[Error] src/components/app/users/$userId: Page.{jsx|tsx} not found',
    )
  })

  test('a Layout does not satisfy a leaf directory', () => {
    expect(errorFor({ 'users/Layout.tsx': LAYOUT_SOURCE })).toBe(
      '[Error] src/components/app/users: Page.{jsx|tsx} not found',
    )
  })

  test('the root is held to the same rule', () => {
    expect(errorFor({})).toBe(
      '[Error] src/components/app: Page.{jsx|tsx} not found',
    )
  })

  test('a 404 does not satisfy the root', () => {
    expect(errorFor({ '404.tsx': PAGE_SOURCE })).toBe(
      '[Error] src/components/app: Page.{jsx|tsx} not found',
    )
  })

  test('a directory with sub-directories needs no Page', () => {
    expect(errorFor({ 'users/$userId/Page.tsx': PAGE_SOURCE })).toBe('')
  })

  test('every failure is reported at once', () => {
    const message = errorFor({
      'photos/Page.tsx': PAGE_SOURCE,
      'users/$userId/': '',
      'orders/': '',
    })

    expect(message.split('\n')).toEqual([
      '[Error] src/components/app/orders: Page.{jsx|tsx} not found',
      '[Error] src/components/app/users/$userId: Page.{jsx|tsx} not found',
    ])
  })
})

describe('import name collisions', () => {
  test('two spellings of the same segment collide', () => {
    expect(
      errorFor({
        'Page.tsx': PAGE_SOURCE,
        'blog/last-week/Page.tsx': PAGE_SOURCE,
        'blog/lastWeek/Page.tsx': PAGE_SOURCE,
      }),
    ).toBe(
      '[Error] duplicate import name `Blog_LastWeek_Page` generated by:\n' +
        '  src/components/app/blog/last-week\n' +
        '  src/components/app/blog/lastWeek',
    )
  })

  test('Page and Layout in one directory do not collide', () => {
    expect(
      errorFor({
        'Layout.tsx': LAYOUT_SOURCE,
        'Page.tsx': PAGE_SOURCE,
      }),
    ).toBe('')
  })
})

describe('default export validation', () => {
  const accepted: Record<string, string> = {
    'function declaration': 'export default function Page() { return null }',
    'anonymous function': 'export default function () { return null }',
    'arrow function': 'export default () => null',
    'class component':
      "import { Component } from 'react'\n" +
      'export default class Page extends Component {}',
    'memo call':
      "import { memo } from 'react'\nexport default memo(() => null)",
    'React.forwardRef call':
      "import React from 'react'\n" +
      'export default React.forwardRef(() => null)',
    'identifier bound to a function':
      'function Page() { return null }\nexport default Page',
    'identifier bound to an arrow':
      'const Page = () => null\nexport default Page',
    'identifier bound to an import':
      "import Page from './elsewhere'\nexport default Page",
    'named default specifier':
      'function Page() { return null }\nexport { Page as default }',
    're-exported default': "export { default } from './elsewhere'",
    'typed component':
      'type Props = { id: string }\n' +
      'export default function Page({ id }: Props) ' +
      '{ return <div>{id}</div> }',
  }

  test.each(Object.entries(accepted))('accepts %s', (_label, source) => {
    expect(errorFor({ 'Page.tsx': source })).toBe('')
  })

  const rejected: Record<string, string> = {
    'a number': 'export default 42',
    'a string': "export default 'nope'",
    'an object': 'export default { render() {} }',
    'an array': 'export default []',
    'a non-component call': 'export default configure(() => null)',
    'an identifier bound to an object': 'const Page = {}\nexport default Page',
  }

  test.each(Object.entries(rejected))('rejects %s', (_label, source) => {
    expect(errorFor({ 'Page.tsx': source })).toBe(
      '[Error] src/components/app/Page.tsx: ' +
        '`default` export is not a valid React component',
    )
  })

  test('reports a missing default export', () => {
    expect(errorFor({ 'Page.tsx': 'export const Page = () => null' })).toBe(
      '[Error] src/components/app/Page.tsx: has no `default` export',
    )
  })

  test('validates Layout files too', () => {
    expect(
      errorFor({
        'Page.tsx': PAGE_SOURCE,
        'Layout.tsx': 'export const Layout = () => null',
      }),
    ).toBe('[Error] src/components/app/Layout.tsx: has no `default` export')
  })

  test('validates the app 404 too', () => {
    expect(
      errorFor({
        'Page.tsx': PAGE_SOURCE,
        '404.tsx': 'export default 42',
      }),
    ).toBe(
      '[Error] src/components/app/404.tsx: ' +
        '`default` export is not a valid React component',
    )
  })
})
